import {
  ReactNode,
} from 'react'
import {
  AiOutlineDashboard,
  AiOutlineAppstore,
  AiOutlineUser,
  AiOutlineSnippets,
  AiOutlineSetting,
  AiOutlineContacts,
  AiOutlineShopping,
  AiOutlineShop,
  AiOutlineTool,
} from 'react-icons/ai'
import {
  RiCoupon2Line,
} from 'react-icons/ri'
import {
  Navigate,
} from 'react-router-dom'
import {
  AccountManagement,
  AddAccount,
  EditAccount,
  Dashboard,
  ForgotPassword,
  Login,
  StoreLogs,
  ResetPassword,
  PlanRevenue,
  Stores,
  Settings,
  PortalLogs,
  SystemLogs,
  PortalUser,
  LatestPlanChanges,
  Plan,
  Group,
  Reports,
  AutomationNotification,
  APIFranchiseToken,
  SMSGatewayConfig,
  SMSTemplate,
  SMTPSetting,
  MailTemplate,
  Support,
  StoreInfo,
  AccountInfo,
  Products,
  PromotionList,
  PromotionAddition,
  ProvisioningProfiles,
  MasterStore,
  ThemesManagement,
  ProfileDetails,
  ApplyProfile,
  EditProfile,
  CreateProfile,
  PromotionEdition,
  ThemeApply,
  CustomerProfileDetails,
  CustomerManagement,
  CustomerOrderRevenue,
  ThemeUpload,
  OrdersRevenue,
  PromotionUtilization,
  PushPromotions,
  Onboarding,
} from './pages'

export interface RouteItem {
  id: string;
  element: ReactNode;
  path: string;
  isPublic?: boolean;
  text?: string;
  icon?: ReactNode;
  permissions?: string[];
}

export const routes: Array<RouteItem> = [
  {
    id: 'login',
    element: <Login />,
    path: 'login',
    isPublic: true,
  },
  {
    id: 'forgot-password',
    element: <ForgotPassword />,
    path: 'forgot-password',
    isPublic: true,
  },
  {
    id: 'reset-password',
    element: <ResetPassword />,
    path: 'reset-password/:token',
    isPublic: true,
  },
  {
    id: 'dashboard',
    element: <Dashboard />,
    path: 'dashboard',
    text: 'Dashboard',
    icon: <AiOutlineDashboard size={18} />,
    permissions: ['stores.get', 'accounts.get', 'tenant_logs.get', 'plan-payments.get', 'plan-changes.get', 'users.get', 'plans.get', 'groups.get', 'configs.id.get'],
  },
  {
    id: 'stores',
    element: <Stores />,
    path: 'stores',
    text: 'Stores',
    permissions: ['stores.get'],
    icon: <AiOutlineAppstore size={18} />,
  },
  {
    id: 'stores/store-info',
    element: <StoreInfo />,
    permissions: ['stores.id.get'],
    path: 'stores/store-info/:id',
  },
  {
    id: 'account',
    text: 'Accounts',
    element: <AccountManagement />,
    path: 'account',
    icon: <AiOutlineUser size={18} />,
    permissions: ['accounts.get'],
  },
  {
    id: 'account/add-account',
    element: <AddAccount />,
    path: 'account/add-account',
    permissions: ['accounts.post'],
  },
  {
    id: 'account/edit-account',
    element: <EditAccount />,
    path: 'account/edit-account',
    permissions: ['accounts.id.put', 'accounts.id.patch'],
  },
  {
    id: 'account/account-info',
    element: <AccountInfo />,
    path: 'account/account-info/:id',
    permissions: ['accounts.id.get'],
  },
  {
    id: 'products',
    element: <Products />,
    path: 'products',
    text: 'Catalog',
    icon: <AiOutlineShopping size={18} />,
    permissions: ['products.get'],
  },
  {
    id: 'promotions',
    element: <PromotionList />,
    path: 'promotions',
    text: 'Promotions',
    icon: <RiCoupon2Line size={18} />,
    permissions: ['promotions.get'],
  },
  {
    id: 'promotions/add-promotion',
    element: <PromotionAddition />,
    path: 'promotions/add-promotion',
    permissions: ['promotions.post'],
  },
  {
    id: 'promotions/edit-promotion/:id',
    element: <PromotionEdition />,
    path: 'promotions/edit-promotion/:id',
    permissions: ['promotions.id.patch'],
  },
  {
    id: 'promotions/push-promotions/:id',
    element: <PushPromotions />,
    path: 'promotions/push-promotions/:id',
    permissions: ['promotions.pushes.post'],
  },
  {
    id: 'themes',
    text: 'Themes',
    path: 'themes',
    element: <ThemesManagement />,
    icon: <AiOutlineTool size={18} />,
    permissions: ['themes.get'],
  },
  {
    id: 'themes/theme-apply/:id',
    element: <ThemeApply />,
    path: 'themes/theme-apply/:id',
    permissions: ['themes.apply.post'],
  },
  {
    id: 'themes/theme-upload',
    element: <ThemeUpload />,
    path: 'themes/theme-upload',
    permissions: ['themes.upload.post'],
  },
  {
    id: 'onboarding',
    element: <Onboarding />,
    path: 'onboarding',
    text: 'Onboarding',
    permissions: ['onboarding.styles.get', 'onboarding.themes.get', 'onboarding.themes.post'],
    icon: <AiOutlineShop size={18} />,
  },
  {
    id: 'provisioning-profiles',
    text: 'Provisioning Profiles',
    path: 'provisioning-profiles',
    element: <ProvisioningProfiles />,
    icon: <AiOutlineShop size={18} />,
    permissions: ['provisioning-profiles.get', 'provisioning-profiles.id.get', 'provisioning-profiles.id.patch'],
  },
  {
    id: 'provisioning-profiles/apply-profile',
    element: <ApplyProfile />,
    path: 'provisioning-profiles/apply-profile/:id',
  },
  {
    id: 'provisioning-profiles/create-profile',
    element: <CreateProfile />,
    path: 'provisioning-profiles/create-profile',
  },
  {
    id: 'provisioning-profiles/edit-profile',
    element: <EditProfile />,
    path: 'provisioning-profiles/edit-profile/:id',
  },
  {
    id: 'provisioning-profiles/profile-details',
    element: <ProfileDetails />,
    path: 'provisioning-profiles/profile-details/:id',
    permissions: ['provisioning-profiles.id.get'],
  },
  {
    id: 'customer-profiles',
    text: 'Customer Profiles',
    path: 'customer-profiles',
    element: <CustomerManagement />,
    icon: <AiOutlineUser size={18} />,
    permissions: ['customers.get'],
  },
  {
    id: 'customer-profiles/customer-details',
    element: <CustomerProfileDetails />,
    path: 'customer-profiles/customer-details/:id',
    permissions: ['customers.get'],
  },
  {
    id: 'customer-profiles/customer-order-revenue',
    element: <CustomerOrderRevenue />,
    path: 'customer-profiles/customer-order-revenue/:id',
    permissions: ['customers.get', 'revenue.get'],
  },
  {
    id: 'reports',
    text: 'Reports',
    path: 'reports',
    element: <Reports />,
    icon: <AiOutlineSnippets size={18} />,
    permissions: ['tenant_logs.get', 'plan-payments.get', 'plan-changes.get'],
  },
  {
    id: 'reports/store-list',
    element: <PlanRevenue />,
    path: 'reports/store-list',
    permissions: ['plan-payments.get'],
  },
  {
    id: 'reports/portal-logs',
    element: <PortalLogs />,
    path: 'reports/portal-logs',
    permissions: ['tenant_logs.get'],
  },
  {
    id: 'reports/plans-update',
    element: <LatestPlanChanges />,
    path: 'reports/plans-update',
    permissions: ['plan-changes.get'],
  },
  {
    id: 'reports/store-logs',
    element: <StoreLogs />,
    path: 'reports/store-logs',
  },
  {
    id: 'reports/orders-revenue',
    element: <OrdersRevenue />,
    path: 'reports/orders-revenue',
  },
  {
    id: 'reports/promotion-utilization',
    element: <PromotionUtilization />,
    path: 'reports/promotion-utilization',
  },
  {
    id: 'reports/system-logs',
    element: <SystemLogs />,
    path: 'reports/system-logs',
  },
  {
    id: 'settings',
    text: 'Settings',
    path: 'settings',
    icon: <AiOutlineSetting size={18} />,
    element: <Settings />,
    permissions: ['users.get', 'plans.get', 'groups.get', 'configs.id.get'],
  },
  {
    id: 'settings/portal-user',
    element: <PortalUser />,
    path: 'settings/portal-user',
    permissions: ['users.get'],
  },
  {
    id: 'settings/plan',
    element: <Plan />,
    path: 'settings/plan',
    permissions: ['plans.get'],
  },
  {
    id: 'settings/master-store',
    element: <MasterStore />,
    path: 'settings/master-store',
    permissions: ['configs.id.get'],
  },
  {
    id: 'settings/group',
    element: <Group />,
    path: 'settings/group',
    permissions: ['groups.get'],
  },
  {
    id: 'settings/automation-notification',
    element: <AutomationNotification />,
    path: 'settings/automation-notification',
    permissions: ['configs.id.get'],
  },
  {
    id: 'settings/api-franchise-token',
    element: <APIFranchiseToken />,
    path: 'settings/api-franchise-token',
    permissions: ['configs.id.get'],
  },
  {
    id: 'settings/sms-sateway-config',
    element: <SMSGatewayConfig />,
    path: 'settings/sms-gateway-config',
  },
  {
    id: 'settings/sms-template',
    element: <SMSTemplate />,
    path: 'settings/sms-template',
  },
  {
    id: 'settings/smtp-setting',
    element: <SMTPSetting />,
    path: 'settings/smtp-setting',
  },
  {
    id: 'settings/mail-template',
    element: <MailTemplate />,
    path: 'settings/mail-template',
    permissions: ['email-templates.get', 'email-templates.put'],
  },
  {
    id: 'support',
    element: <Support />,
    path: 'support',
    text: 'Support',
    icon: <AiOutlineContacts size={18} />,
  },
  {
    id: 'not-found',
    path: '*',
    element: <Navigate to="/login" />,
  },
]

export const pageTypes = {
  noFrame: ['', 'login', 'reset-password', 'forgot-password'],
}
