# docker-compose.yml

version: "3"
services:
  nest_postgres_dev:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=Asia/Shanghai
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/pgdata'
    ports:
      - "5432:5432"

  redis_dev:
    restart: always
    image: redis:alpine
    ports:
      - "6379:6379"

  nest_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./apps/api/.env
    restart: always
    ports:
      - 3000:3000

volumes:
  postgres_data:
